name: 'Comment Finder'
description:
  'Check if a specific user or team member has commented on the current PR with
  given keywords'
author: 'awcodify@gmail.com'

branding:
  icon: 'search'
  color: 'blue'

inputs:
  authors:
    description:
      'GitHub usernames or team slugs separated by commas. This will be used to
      filter comments by the author'
    required: true
  keywords:
    description: 'Comment keywords to search for (comma-separated)'
    required: true
    default: 'approve,yes,LGTM'
  token:
    description: 'GitHub token'
    required: true

runs:
  using: node20
  main: dist/index.js
